name: Production Deployment
on:
    push:
        branches:
            - production

jobs:
    build-trigger:
        uses: ./.github/workflows/deploy.yml
        with:
            env: production
        secrets: inherit